#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Getopt::Long qw(:config bundling no_ignore_case auto_help auto_version);
use Test::Rinci::CmdLine;

my %opts = (
    exclude_scripts => [],
    wrap_function => 1,
    test_function_examples => 1,
);
GetOptions(
    'exclude-script=s' => $opts{exclude_scripts},
    'W' => sub { $opts{wrap_function} = 0 },
    'E' => sub { $opts{test_function_examples} = 0 },
);

if (@ARGV) {
    metadata_in_scripts_ok(\%opts, \@ARGV);
} else {
    metadata_in_all_scripts_ok(\%opts);
}

1;
# ABSTRACT: Test Rinci metadata in scripts under script/ and bin/
# PODNAME:

=head1 SYNOPSIS

In your dist directory:

 % test-rinci-cmdline [options]

Or, to test individual scripts:

 % test-rinci-cmdline [options] script1.pl ...


=head1 DESCRIPTION

This script is an command-line interface for L<Test::Rinci::CmdLine>'s
C<metadata_in_all_scripts_ok()> function.


=head1 OPTIONS

=over

=item * --exclude-script=s

Exclude a script path. Can be specified multiple times.

=item * -E

This sets C<test_function_examples> to 0.

=item * -W

This sets C<wrap_function> to 0.

=back


=head1 SEE ALSO

L<Test::Rinci::CmdLine>

=cut
